// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGBMdox7vGND_2U8qDQBFum70vTe-uTs0',
    appId: '1:644101839836:web:c1e313767365a3e554cd19',
    messagingSenderId: '644101839836',
    projectId: 'caleg-f670d',
    authDomain: 'caleg-f670d.firebaseapp.com',
    storageBucket: 'caleg-f670d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA43FXBDbu-rhSCknOy7MmF4NT0K-zNGRA',
    appId: '1:644101839836:android:64df917ecb77d7f454cd19',
    messagingSenderId: '644101839836',
    projectId: 'caleg-f670d',
    storageBucket: 'caleg-f670d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0855RIe0Dpz-OGaOhldNJ6M5HGO47Xtw',
    appId: '1:644101839836:ios:473bfa9ae018f65c54cd19',
    messagingSenderId: '644101839836',
    projectId: 'caleg-f670d',
    storageBucket: 'caleg-f670d.appspot.com',
    iosClientId: '644101839836-q2j2f7qblu88ndpkrjmnf0f0bl8r5kif.apps.googleusercontent.com',
    iosBundleId: 'com.example.caleg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0855RIe0Dpz-OGaOhldNJ6M5HGO47Xtw',
    appId: '1:644101839836:ios:473bfa9ae018f65c54cd19',
    messagingSenderId: '644101839836',
    projectId: 'caleg-f670d',
    storageBucket: 'caleg-f670d.appspot.com',
    iosClientId: '644101839836-q2j2f7qblu88ndpkrjmnf0f0bl8r5kif.apps.googleusercontent.com',
    iosBundleId: 'com.example.caleg',
  );
}
